services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: self_healing_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - postgres

  user-service:
    build: ./services/user-service
    container_name: user-service
    restart: always
    ports:
      - "3002:3002"
    env_file:
      - .env

  order-service:
    build: ./services/order-service
    container_name: order-service
    restart: always
    ports:
      - "3003:3003"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    restart: always
    ports:
      - "3004:3004"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  monitoring-server:
    build: ./services/monitoring-server

    container_name: monitoring-server

    ports:
      - "5001:5001"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

    depends_on:
      - auth-service
      - user-service
      - order-service
      - payment-service

  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana

    container_name: grafana

    ports:
    - "3006:3000"

    environment:
    - GF_SECURITY_ALLOW_EMBEDDING=true

    volumes:
    - grafana-storage:/var/lib/grafana

    
volumes:
  postgres-data:
  grafana-storage:
